services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: flyway
      MYSQL_PASSWORD: flywaypw
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
  flyway:
    image: flyway/flyway
    container_name: flyway
    environment:
      FLYWAY_URL: jdbc:mysql://db:3306/mydatabase
      FLYWAY_USER: flyway
      FLYWAY_PASSWORD: flywaypw
      FLYWAY_CLEAN_DISABLED: false # Allow clean for development purposes
    volumes:
      - ./sql:/flyway/sql
    command: -connectRetries=60 info
    # command: -connectRetries=60 migrate
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
networks:
  default:
    driver: bridge
